'use strict';
/**
 * codegen-secret.js — 构建期密钥注入
 *
 * v4.2.1 起授权改为 Ed25519，客户端不再生成或打包授权签发密钥。
 * 本脚本只生成试用代理的独立运行时配置；provider API key 必须留在服务端。
 */
const fs = require('fs');
const path = require('path');

const root = path.resolve(__dirname, '..');

// 代理共享密钥（APP_PROXY_KEY）：仅用于客户端访问韩国代理，不是 provider API key。
let appProxyKey = '';
const appKeyFile = path.join(root, '.app-proxy-key');
if (fs.existsSync(appKeyFile)) {
  try { appProxyKey = require(appKeyFile).APP_PROXY_KEY || ''; } catch (e) { /* ignore */ }
}
if (!appProxyKey) appProxyKey = process.env.APP_PROXY_KEY || '';

// provider key（例如 sk-*）一旦进入此文件就会随客户端运行时存在，必须硬失败。
if (/^sk-[A-Za-z0-9]/.test(appProxyKey)) {
  console.error('[codegen-secret] 拒绝生成：provider API key 不得作为 APP_PROXY_KEY 注入客户端');
  process.exit(1);
}

const outFile = path.join(root, 'proxy-secret.generated.js');

// 编码存储：XOR(0x5A) 后 base64；这里仅是代理鉴权令牌，不是 provider API key。
// 运行时由 main.js require 后还原为明文，用于向代理鉴权。
function encodeProxyKey(k) {
  const buf = Buffer.from(k, 'utf8');
  for (let i = 0; i < buf.length; i++) buf[i] ^= 0x5A;
  return buf.toString('base64');
}
const enc = encodeProxyKey(appProxyKey);
const content =
  '// AUTO-GENERATED by scripts/codegen-secret.js — DO NOT COMMIT / DO NOT EDIT\n' +
  '// APP_PROXY_KEY 仅为代理鉴权令牌，以 XOR(0x5A)+base64 编码存储。provider API key 不得出现在客户端。\n' +
  'const __xj_proxy_enc = ' + JSON.stringify(enc) + ';\n' +
  'module.exports = { APP_PROXY_KEY: (function () { const b = Buffer.from(__xj_proxy_enc, \'base64\'); for (let i = 0; i < b.length; i++) b[i] ^= 0x5A; return b.toString(\'utf8\'); })() };\n';
if (!fs.existsSync(outFile) || fs.readFileSync(outFile, 'utf8') !== content) {
  fs.writeFileSync(outFile, content);
  console.log('[codegen-secret] 已生成 proxy-secret.generated.js（不含授权签发密钥）');
} else {
  console.log('[codegen-secret] proxy-secret.generated.js 内容未变化，复用现有文件');
}
