'use strict';
/**
 * codegen-secret.js — 构建期密钥注入
 *
 * 目标：源码仓库与 git 历史中永远不含 LICENSE_SECRET 字面量。
 * 密钥只在两处存在：
 *   1) 开发者本机 .license-secret（gitignored，不入库）
 *   2) CI 环境变量 LICENSE_SECRET（GitHub repo secret，不入库）
 * 本脚本把密钥写进 secret.generated.js（gitignored，会被 electron-builder 打进 exe），
 * 运行时 license-core.js 从 secret.generated.js 读取。
 */
const fs = require('fs');
const path = require('path');

const root = path.resolve(__dirname, '..');
let secret = '';

// 1) 本机 .license-secret（gitignored）
const licFile = path.join(root, '.license-secret');
if (fs.existsSync(licFile)) {
  try { secret = require(licFile).SECRET || ''; } catch (e) { /* ignore */ }
}

// 2) CI / 构建环境注入的环境变量
if (!secret) secret = process.env.LICENSE_SECRET || '';

// 3) 兜底：复用上一步已生成的 secret.generated.js（CI 多 step 间文件持久，但 env 不自动透传）
if (!secret) {
  const gen = path.join(root, 'secret.generated.js');
  if (fs.existsSync(gen)) { try { secret = require(gen).SECRET || ''; } catch (e) { /* ignore */ } }
}

if (!secret) {
  console.error('[codegen-secret] 未找到 LICENSE_SECRET：请在 .license-secret 或环境变量 LICENSE_SECRET 中提供');
  process.exit(1);
}

const outFile = path.join(root, 'secret.generated.js');
const content =
  '// AUTO-GENERATED by scripts/codegen-secret.js — DO NOT COMMIT / DO NOT EDIT\n' +
  'module.exports = { SECRET: ' + JSON.stringify(secret) + ' };\n';
fs.writeFileSync(outFile, content);
console.log('[codegen-secret] 已生成 secret.generated.js（密钥不写入源码仓库）');
