'use strict';
/**
 * codegen-version.js — 构建期版本注入
 *
 * 根因：设置页「关于」的版本号此前依赖「运行时桥接 app.getVersion() + 写死兜底 v1.0.5」。
 * 一旦某一环（preload/桥接/打包清单）未如预期，就静默退回写死版本，表现为「装新包后版本号不更新」。
 *
 * 修复：在构建期把 package.json 的真实 version 写进 version.generated.js（gitignored，
 * 被 electron-builder 打进 exe）。渲染进程（设置页）优先读此文件注入的版本，
 * 与安装包强制绑定，桥接只作为 dev 兜底。
 */
const fs = require('fs');
const path = require('path');

const root = path.resolve(__dirname, '..');
let version = '0.0.0';
try {
  const pkg = JSON.parse(fs.readFileSync(path.join(root, 'package.json'), 'utf8'));
  version = pkg.version || version;
} catch (e) {
  console.error('[codegen-version] 读取 package.json 失败，回退 0.0.0:', (e && e.message) || e);
}
if (!/^\d+\.\d+\.\d+/.test(version)) {
  console.error('[codegen-version] 版本号格式异常:', version);
  process.exit(1);
}

const outFile = path.join(root, 'version.generated.js');
const content =
  '// AUTO-GENERATED by scripts/codegen-version.js — DO NOT COMMIT / DO NOT EDIT\n' +
  'module.exports = { VERSION: ' + JSON.stringify(version) + ' };\n';
fs.writeFileSync(outFile, content);
console.log('[codegen-version] 已生成 version.generated.js 版本=' + version);
