# -*- coding: utf-8 -*-
"""Gen app/js/knowledge.builtins.js — 打包大师知识库 .md 文件。
构建期/dev 启动时运行，把 app/masters/knowledge/*.md 读取并 Base64 编码进 JS 常量，
供渲染进程运行时通过 window.Knowledge.byTemp(masterKey, talkTemp) 解码加载。

复用 gen-prompts-builtin.py 的 Base64 编码模式。
"""
import base64, os, json, sys

BASE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
KB_DIR = os.path.join(BASE, 'app', 'masters', 'knowledge')
OUT = os.path.join(BASE, 'app', 'js', 'knowledge.builtins.js')

if not os.path.isdir(KB_DIR):
    print(f'ERROR: KB_DIR not found: {KB_DIR}', file=sys.stderr)
    sys.exit(1)

# key -> { slot: text }
KB = {}

for fn in os.listdir(KB_DIR):
    if not fn.endswith('.md'):
        continue
    path = os.path.join(KB_DIR, fn)
    with open(path, 'r', encoding='utf-8') as f:
        text = f.read()
    # e.g. winnicott-knowledge.md -> key=winnicott, slot=knowledge
    # e.g. winnicott-skill-only.md -> key=winnicott, slot=skill-only
    base = fn[:-3]  # strip .md
    # Split on first hyphen after the master key prefix
    # Master keys: winnicott, lacan, freud, klein, jung, bion, rogers,
    #   beck, yalom, adler, sue-johnson, consultant-a
    known_keys = ['winnicott','lacan','freud','klein','jung','bion','rogers',
                  'beck','yalom','adler','sue-johnson','consultant-a']
    key = None
    slot = None
    for k in known_keys:
        if base.startswith(k + '-'):
            key = k
            slot = base[len(k)+1:]
            break
    if not key:
        print(f'WARNING: skip {fn} (unknown master key)')
        continue
    if key not in KB:
        KB[key] = {}
    KB[key][slot] = text

def b64(s):
    return base64.b64encode(s.encode('utf-8')).decode('ascii')

lines = []
lines.append('/** @internal 大师知识库（构建期打包）— 自动生成，勿手改 */')
lines.append('/* Generated by scripts/gen-knowledge-builtins.py */')
lines.append("const Knowledge = (() => {")
lines.append("  'use strict';")
lines.append("  function d(b64) {")
lines.append("    try {")
lines.append("      const bin = atob(b64);")
lines.append("      const bytes = new Uint8Array(bin.length);")
lines.append("      for (let i = 0; i < bin.length; i++) bytes[i] = bin.charCodeAt(i);")
lines.append('      return new TextDecoder("utf-8").decode(bytes);')
lines.append("    } catch (e) { return ''; }")
lines.append("  }")
lines.append("")
lines.append("  const RAW = {")
for key in sorted(KB.keys()):
    slots = KB[key]
    lines.append(f'    {json.dumps(key)}: {{')
    for slot in sorted(slots.keys()):
        lines.append(f'      {json.dumps(slot)}: "{b64(slots[slot])}",')
    lines.append('    },')
lines.append("  };")
lines.append("")
lines.append("  function get(key, slot) {")
lines.append("    const m = RAW[key];")
lines.append("    if (!m) return '';")
lines.append("    return m[slot] ? d(m[slot]) : '';")
lines.append("  }")
lines.append("")
lines.append("  // Chat 项目温度区间映射：")
lines.append("  //   <=40: emotional (情感逐字稿, 仅温尼科特有) -> fallback perspective")
lines.append("  //   41-70: perspective (大师人格视角)")
lines.append("  //   >70: knowledge (完整知识库) + skill")
lines.append("  function byTemp(key, temp) {")
lines.append("    const m = RAW[key] || {};")
lines.append("    const t = temp || 60;")
lines.append("    if (t <= 40 && m['emotional']) return d(m['emotional']);")
lines.append("    if (t <= 40 && m['perspective']) return d(m['perspective']);")
lines.append("    if (t <= 70 && m['perspective']) return d(m['perspective']);")
lines.append("    let result = '';")
lines.append("    if (m['knowledge']) result = d(m['knowledge']);")
lines.append("    if (m['skill-only']) result += '\\\\n\\\\n' + d(m['skill-only']);")
lines.append("    if (!result && m['perspective']) result = d(m['perspective']);")
lines.append("    return result;")
lines.append("  }")
lines.append("")
lines.append("  function allKeys() { return Object.keys(RAW); }")
lines.append("  function slotsOf(key) { return RAW[key] ? Object.keys(RAW[key]) : []; }")
lines.append("")
lines.append("  return { get, byTemp, allKeys, slotsOf };")
lines.append("})();")
lines.append("")
lines.append("if (typeof window !== 'undefined') { window.Knowledge = Knowledge; }")
lines.append("")

result = '\n'.join(lines)
with open(OUT, 'w', encoding='utf-8') as f:
    f.write(result)

print(f'WRITTEN {OUT}')
print(f'  size={os.path.getsize(OUT)} bytes')
print(f'  masters={len(KB)}')
for k in sorted(KB.keys()):
    print(f'    {k}: {sorted(KB[k].keys())}')
