const test = require('node:test');
const assert = require('node:assert/strict');
const router = require('../../app/js/clinical-agent-router.js');
test('all six intent families route', () => { [['请做反移情分析','countertransference-analysis'],['session review please','session-review'],['个案概念化','case-conceptualization'],['next session hypotheses','next-session-hypotheses'],['督导问题','supervision-question-builder'],['multi-school comparison','multi-school-comparison']].forEach(([text,id]) => assert.equal(router.route(text).taskId,id)); });
test('standard supervision phrases route explicitly and question builder stays distinct', () => { [['生成整体印象','supervision-preview'],['AI 督导','supervision-preview'],['督导整体印象','supervision-preview'],['督导问题生成','supervision-question-builder']].forEach(([text,id]) => assert.equal(router.route(text).taskId,id)); });
test('whitespace normalization preserves next-session and session-review intents', () => { ['next session hypotheses', 'next\tsession hypotheses', 'next\nsession hypotheses'].forEach((text) => assert.equal(router.route(text).taskId, 'next-session-hypotheses')); assert.equal(router.route('  session    review  ').taskId, 'session-review'); });
test('malformed and ambiguous input never guesses', () => { assert.equal(router.route('').reason,'malformed-input'); assert.equal(router.route('请帮我分析一下').reason,'intent-unclear'); assert.equal(router.route('session review and case conceptualization').reason,'intent-unclear'); });
test('preview validates sources and leaks metadata only', () => { const out=router.preview('session-review',{sources:[{kind:'session',id:'s1',clientId:'c1'}]}); assert.equal(out.status,'awaiting-confirmation'); assert.deepEqual(out.sources,[{kind:'session',id:'s1'}]); assert.equal('content' in out,false); assert.equal(router.preview('session-review',{sources:[]}).reason,'required-source-missing'); assert.equal(router.preview('session-review',{sources:[{kind:'session',id:'s1',clientId:'c1'},{kind:'session',id:'s2',clientId:'c2'}]}).reason,'cross-client-source-mismatch'); });
test('metadata is defensive', () => { const a=router.listIntents(); assert.throws(()=>a.push(1)); a[0].phrases.push('x'); assert.equal(router.listIntents()[0].phrases.includes('x'),false); });
