const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const path = require('node:path');
const file = path.join(__dirname, '../../app/js/clinical-agent-tasks.js');
const source = fs.readFileSync(file, 'utf8');
const context = vm.createContext({});
vm.runInContext(source, context, { filename: file });
const api = context.ClinicalAgentTasks;
const ids = ['countertransference-analysis', 'session-review', 'case-conceptualization', 'next-session-hypotheses', 'supervision-question-builder', 'multi-school-comparison', 'supervision-preview'];
const sourceFor = (kind, extra = {}) => ({ kind, id: kind + '-1', ...extra });

assert.ok(api && Object.isFrozen(api));
assert.deepEqual(Array.from(api.listTaskIds()), ['countertransference-analysis', 'session-review', 'case-conceptualization', 'next-session-hypotheses', 'supervision-question-builder', 'multi-school-comparison', 'supervision-preview']);
assert.deepEqual(Array.from(api.EFFECTS), ['read', 'retrieve-sensitive', 'draft', 'durable-write', 'export', 'external-send', 'destructive', 'config']);
for (const id of ids) {
  const spec = api.getTask(id);
  assert.ok(Object.isFrozen(spec));
  assert.equal(spec.previewFirst, true);
  assert.equal(spec.confirmationBoundary, 'human-confirmation-before-durable-write');
  assert.ok(spec.outputSections.length > 0);
  assert.equal(api.project(id).taskId, id);
  assert.equal(api.project(id).effect, spec.effect);
}
assert.equal(api.getTask('unknown'), null);
assert.equal(api.project('unknown'), null);
assert.equal(api.validate('unknown', {} ).reason, 'unknown-task');
assert.equal(api.validate('session-review', { effect: 'bogus', outputDisposition: 'preview', sources: [sourceFor('session')] }).reason, 'unknown-effect');
assert.equal(api.validate('session-review', { effect: 'retrieve-sensitive', outputDisposition: 'final', sources: [sourceFor('session')] }).reason, 'invalid-output-disposition');
assert.equal(api.validate('session-review', { effect: 'retrieve-sensitive', outputDisposition: 'preview', sources: [] }).reason, 'required-source-missing');
assert.equal(api.validate('session-review', { effect: 'retrieve-sensitive', outputDisposition: 'preview', sources: [sourceFor('session', { clientId: 'c1' }), sourceFor('material', { clientId: 'c2' })], context: { clientId: 'c1' } }).reason, 'cross-client-source-mismatch');
assert.equal(api.validate('session-review', { effect: 'retrieve-sensitive', outputDisposition: 'preview', sources: [sourceFor('session', { stale: true })] }).reason, 'stale-snapshot');
assert.equal(api.validate('session-review', { effect: 'retrieve-sensitive', outputDisposition: 'preview', sources: [sourceFor('session')], context: { snapshotStale: true } }).reason, 'stale-snapshot');
assert.equal(api.validate('session-review', { effect: 'retrieve-sensitive', outputDisposition: 'preview', sources: [sourceFor('session')], context: { stale: true } }).reason, 'stale-snapshot');
assert.equal(api.validate('session-review', { effect: 'retrieve-sensitive', outputDisposition: 'preview', sources: [sourceFor('session')], context: { snapshot: { stale: true } } }).reason, 'stale-snapshot');
assert.equal(api.validate('session-review', { effect: 'retrieve-sensitive', outputDisposition: 'preview', sources: [sourceFor('session', { clientId: 'c1' }), sourceFor('material', { clientId: 'c2' })] }).reason, 'cross-client-source-mismatch');
assert.equal(api.validate('session-review', { effect: 'retrieve-sensitive', outputDisposition: 'preview', sources: [sourceFor('session', { clientId: 'c1' }), sourceFor('material', { clientId: 'c1' })] }).ok, true);
assert.equal(api.validate('session-review', { effect: 'retrieve-sensitive', outputDisposition: 'preview', sources: [sourceFor('material')] }).reason, 'required-source-missing');
assert.equal(api.validate('session-review', { effect: 'retrieve-sensitive', outputDisposition: 'preview', sources: [sourceFor('session')] }).ok, true);
assert.equal(api.validate('session-review', { effect: 'draft', outputDisposition: 'preview', sources: [sourceFor('session')] }).reason, 'effect-mismatch');
assert.equal(api.validate('session-review', { effect: 'retrieve-sensitive', outputDisposition: 'preview', sources: [sourceFor('session')], confirmed: true }).ok, true);
assert.equal(api.getTask('supervision-preview').allowEmptySources, true);
assert.equal(api.validate('supervision-preview', { effect: 'draft', outputDisposition: 'preview', sources: [], context: {} }).ok, true);
assert.equal(api.validate('supervision-preview', { effect: 'draft', outputDisposition: 'preview', sources: [], context: { clientId: 'c1' } }).reason, 'required-source-missing');
assert.equal(api.validate('supervision-preview', { effect: 'draft', outputDisposition: 'preview', sources: [], context: { origin: { materialId: 'm1' } } }).reason, 'required-source-missing');
assert.equal(api.validate('supervision-preview', { effect: 'draft', outputDisposition: 'preview', sources: [], context: { origin: { supervisionId: 'sup1' } } }).reason, 'required-source-missing');
assert.equal(api.validate('supervision-preview', { effect: 'draft', outputDisposition: 'preview', sources: [sourceFor('client')] }).ok, true);
const projected = api.project('case-conceptualization');
assert.equal('clinicalBody' in projected, false);
api.TASKS['session-review'] = {};
assert.equal(api.getTask('session-review').id, 'session-review');
assert.equal(api.getTask('session-review').id, 'session-review');
console.log('clinical-agent-tasks contract: PASS');
