const test = require('node:test');
const assert = require('node:assert/strict');
const Run = require('../../app/js/clinical-agent-run.js');
const base = () => Run.create({ runId: 'r1', taskId: 'session-review', origin: 'router', sources: [{ id: 's1', kind: 'session' }], snapshotKey: 'snap-1' });
test('exports immutable statuses and creates planned/awaiting-context', () => { assert.deepEqual(Run.STATUSES, ['planned','awaiting-context','awaiting-confirmation','running','draft-ready','stale','failed','cancelled','adopted','persisted']); assert.equal(base().status, 'planned'); assert.equal(base().metadata.outputDisposition, 'preview'); assert.equal(Run.create({runId:'r2',taskId:'t',status:'awaiting-context',outputDisposition:'draft'}).metadata.outputDisposition, 'draft'); assert.throws(() => Run.create({runId:'r3',taskId:'t',outputDisposition:'answer'})); assert.throws(() => Run.create({runId:'',taskId:'t'})); });
test('transition matrix and prerequisites', () => { let r=base(); for (const s of ['awaiting-confirmation','running','draft-ready','adopted','persisted']) r=Run.transition(r,s); assert.equal(r.status,'persisted'); for (const pair of [['planned','persisted'],['awaiting-confirmation','persisted'],['failed','running']]) assert.equal(Run.canTransition(...pair),false); assert.throws(()=>Run.transition(base(),'persisted')); });
test('stale/cancelled preserve metadata and inputs stay immutable', () => { const r=base(); const before=JSON.stringify(r); const stale=Run.transition(r,'awaiting-context'); const stale2=Run.transition(stale,'awaiting-confirmation'); const stale3=Run.transition(stale2,'stale'); assert.equal(stale3.metadata.error,'stale'); const cancelled=Run.transition(r,'cancelled',{cancellation:{reason:'user'}}); assert.deepEqual(cancelled.metadata.cancellation,{reason:'user'}); assert.equal(JSON.stringify(r),before); assert(Object.isFrozen(stale3.metadata)); });
test('appendStep bounds metadata and project leaks no body/prompt', () => { const r=base(); const next=Run.appendStep(r,{stepId:'a',status:'running',task:'read',effect:'read',retryable:false}); assert.equal(next.steps.length,1); assert.throws(()=>Run.appendStep(r,{stepId:'x',status:'running',outputDisposition:'draft'})); assert.throws(()=>Run.appendStep(r,{stepId:'x',status:'running',prompt:'secret'})); const draft=Run.transition(Run.transition(r,'awaiting-confirmation'),'running'); const ready=Run.transition(draft,'draft-ready'); const p=Run.project(ready); assert.equal(p.outputDisposition,'preview'); assert.equal('prompt' in p,false); assert.equal('body' in p,false); assert.equal('answer' in p,false); assert.equal(JSON.stringify(p).includes('secret'),false); });
test('mutation-sensitive guards remain active', () => { const r=base(); assert.throws(()=>Run.transition(r,'adopted')); assert.throws(()=>Run.transition(r,'persisted')); assert.throws(()=>Run.appendStep(r,{stepId:'x',status:'running',content:'clinical body'})); });
